repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: uv run bandit --confidence-level 'medium' --severity-level 'medium' --exclude test
        language: system
        pass_filenames: true
        types: ['python']

      - id: sphinx-lint
        name: sphinx-lint
        entry: uv run sphinx-lint
        language: system
        pass_filenames: true
        types: ['rst']

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        pass_filenames: true
        types: ['python']

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        pass_filenames: true
        types: ['python']
