import logging
import sys
import warnings
from pathlib import Path

repository_directory = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(repository_directory))

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=RuntimeWarning)
    from parsons import _CONNECTORS  # type: ignore

logger = logging.getLogger(__name__)

lines = [
    "# This file is automatically generated by generate_init_pyi.py.",
    "# Do not edit this file manually.",
    "# If it is out of date, run 'python types/generate_init_pyi'.",
    "",
]

for name, module_path in sorted(_CONNECTORS.items()):
    lines.append(f"from {module_path} import {name} as {name}")

stub_content = "\n".join(lines) + "\n"

output_path = repository_directory / "parsons" / "__init__.pyi"
output_path.write_text(stub_content)

logger.info(f"Successfully generated {output_path}")
