import datetime
import logging

from requests.auth import HTTPBasicAuth

from parsons import Table
from parsons.utilities import check_env
from parsons.utilities.api_connector import APIConnector

logger = logging.getLogger(__name__)

URI = "https://donorbox.org/api/v1"


class Donorbox:
    """
    Instantiate Donorbox class.

    Args:
        donorbox_account_email:
            The email associated with your Donorbox account. Can be passed as
            argument or set as ``DONORBOX_ACCOUNT_EMAIL`` environment variable.
        donorbox_api_key:
            The API key generated by Donorbox for your account. Can be passed as
            argument or set as ``DONORBOX_API_KEY`` environment variable.

    """

    def __init__(self, email: str | None = None, api_key: str | None = None):
        self.email: str = check_env.check("DONORBOX_ACCOUNT_EMAIL", email)
        self.api_key: str = check_env.check("DONORBOX_API_KEY", api_key)
        self.uri = URI
        self.client = APIConnector(self.uri, auth=HTTPBasicAuth(self.email, self.api_key))

    def get_campaigns(self, **kwargs) -> Table:
        """
        Get information on campaigns.

        Args:
            id (int or str):
                The ID of the campaign to get.
                If both id and name are omitted, returns all campaigns.
            name (str):
                The name of the campaign to get.
                If both id and name are omitted, returns all campaigns.
            order (str):
                Valid values are ``asc`` and ``desc``.
                If not supplied, order is descending by default.
            page (int):
                Donorbox supports pagination for larger results.
                Use the page to track your progress.
            per_page (int):
                Results per page when using pagination.
                Default is 50, maximum is 100.

        """
        result = self.client.request("campaigns", "GET", params=kwargs)
        data = result.json()

        return Table(data)

    def get_donations(self, **kwargs) -> Table:
        """
        Get information on donations.

        Args:
            email (str):
                Filter's donations by donor's email
            date_from (str):
                Filters donations to those started on or after the provided date.
                Valid formats: ``YYYY-mm-dd YYYY/mm/dd`` and ``YYYYmmdd dd-mm-YYYY``
                If an incorrectly formatted date is provided, an error is raised.
            date_to (str):
                Filters donations to those started before the provided date.
                Valid formats: ``YYYY-mm-dd YYYY/mm/dd`` and ``YYYYmmdd dd-mm-YYYY``
                If an incorrectly formatted date is provided, an error is raised.
            campaign_name (str):
                Filters by the campaign title that you have defined in Donorbox.
            campaign_id (int or str):
                Filters by Donorbox campaign id.
            donation_id (int or str):
                Filters by Donorbox donations id.
            first_name (str):
                Filters by donor's first name.
            last_name (str):
                Filters by donor's last name.
            donor_id (int or str):
                Filters by Donorbox donor id.
            amount_min (int or str):
                Gets all donations above the provided minimum.
            amount_max (int or str):
                Gets all donations below the provided maximum.
            order (str):
                Valid values are ``asc`` and ``desc``.
                If not supplied, order is descending by default.
            page (int):
                Donorbox supports pagination for larger results.
                Use the page to track your progress.
            per_page (int):
                Results per page when using pagination.
                Default is 50, maximum is 100.

        """
        # switch variable names
        if "amount_max" in kwargs:
            kwargs["amount[usd][max]"] = kwargs.pop("amount_max")
        if "amount_min" in kwargs:
            kwargs["amount[usd][min]"] = kwargs.pop("amount_min")
        if "donation_id" in kwargs:
            kwargs["id"] = kwargs.pop("donation_id")

        self._check_date_helper(kwargs)
        data = self.client.get_request(url="donations", params=kwargs)

        return Table(data)

    def get_donors(self, **kwargs) -> Table:
        """
        Get information on donors.

        Args:
            donor_id (str or int):
                Filters by donor ID.
            first_name (str):
                Filters by donor's first name.
            last_name (str):
                Filters by donor's last name.
            donor_name (str):
                Filter by donor's full name
            email (str):
                Filter's donations by donor's email
            order (str):
                Valid values are ``asc`` and ``desc``.
                If not supplied, order is descending by default.
            page (int):
                Donorbox supports pagination for larger results.
                Use the page to track your progress.
            per_page (int):
                Results per page when using pagination.
                Default is 50, maximum is 100.

        """
        if "donor_id" in kwargs:
            kwargs["id"] = kwargs.pop("donor_id")  # switch to Donorbox's (less specific) name

        data = self.client.get_request(url="donors", params=kwargs)

        return Table(data)

    def get_plans(self, **kwargs) -> Table:
        """
        Get information on plans.

        Args:
            email (str):
                Filter's plans by donor's email address.
            date_from (str):
                Filters plans to those started on or after the provided date.
                Valid formats: ``YYYY-mm-dd YYYY/mm/dd`` and ``YYYYmmdd dd-mm-YYYY``
                If an incorrectly formatted date is provided, an error is raised.
            date_to (str):
                Filters plans to those started before the provided date.
                Valid formats: ``YYYY-mm-dd YYYY/mm/dd`` and ``YYYYmmdd dd-mm-YYYY``
                If an incorrectly formatted date is provided, an error is raised.
            campaign_id (int or str):
                Filters by Donorbox campaign id.
            campaign_name (str):
                Filters by the campaign title that you have defined in Donorbox.
            donor_id (str or int):
                Filters by donor ID.
            first_name (str):
                Filters by donor's first name.
            last_name (str):
                Filters by donor's last name.
            donor_name (str):
                Filter by donor's full name
            order (str):
                Valid values are ``asc`` and ``desc``.
                If not supplied, order is descending by default.
            page (int):
                Donorbox supports pagination for larger results.
                Use the page to track your progress.
            per_page (int):
                Results per page when using pagination.
                Default is 50, maximum is 100.

        """
        self._check_date_helper(kwargs)
        data = self.client.get_request(url="plans", params=kwargs)

        return Table(data)

    def _check_date_helper(self, params: dict[str, str]) -> None:
        """
        Searches through params for a date parameter and if found, calls format helper.

        Args:
            params: Dictionary of parameters to be passed to endpoint.

        """
        if "date_from" in params and params["date_from"] is not None:
            self._date_format_helper(params["date_from"])

        if "date_to" in params and params["date_to"] is not None:
            self._date_format_helper(params["date_to"])

    def _date_format_helper(self, date_string: str) -> None:
        """
        Checks date format and warns if invalid (internal).

        Valid formats: ``YYYY-mm-dd``, ``YYYY/mm/dd``, ``YYYYmmdd``, and ``dd-mm-YYYY``

        Args:
            date_string:
                Date in a string format to be checked against Donorbox's valid options.

        Raises:
            ValueError: If the date is not a valid format.

        """
        valid_formats = ["%Y-%m-%d", "%d-%m-%Y", "%Y/%m/%d", "%Y%m%d"]
        for str_format in valid_formats:
            try:
                datetime.datetime.strptime(date_string, str_format)
                return

            except ValueError:
                continue

        raise ValueError(
            f"The date you supplied, {date_string}, is not a valid Donorbox format. "
            "Try the following formats: YYYY-mm-dd YYYY/mm/dd YYYYmmdd dd-mm-YYYY"
        )
