test_get_app_tables = [
  {
    "alias": "_DBID_MEMBERSHIP",
    "created": "2020-09-01T20:16:15Z",
    "defaultSortFieldId": 4,
    "defaultSortOrder": "ASC",
    "description": "",
    "id": "abcdef",
    "keyFieldId": 3,
    "name": "Members",
    "nextFieldId": 100,
    "nextRecordId": 250,
    "pluralRecordName": "Members",
    "singleRecordName": "Member",
    "sizeLimit": "500 MB",
    "spaceRemaining": "500 MB",
    "spaceUsed": "50 KB",
    "updated": "2020-10-11T15:25:53Z"
  },
  {
    "alias": "_DBID_MEETINGS",
    "created": "2020-07-10T03:16:15Z",
    "defaultSortFieldId": 7,
    "defaultSortOrder": "DESC",
    "description": "",
    "id": "brqdmcesd",
    "keyFieldId": 7,
    "name": "Meetings",
    "nextFieldId": 18,
    "nextRecordId": 81,
    "pluralRecordName": "Meetings",
    "singleRecordName": "Meeting",
    "sizeLimit": "500 MB",
    "spaceRemaining": "500 MB",
    "spaceUsed": "100 KB",
    "updated": "2020-09-11T14:17:23Z"
  }]
