name: Dependency review

on: [pull_request]

permissions: read-all

jobs:
   dependency-review:
    name: Dependency review

    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
              api.deps.dev:443
              api.github.com:443
              api.securityscorecards.dev:443
              github.com:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/dependency-review-action@05fe4576374b728f0c523d6a13d64c25081e0803
