name: PR labeler

on:
  pull_request_target:
    types: [opened, edited, reopened, ready_for_review, synchronize]

permissions: read-all

jobs:
  label-from-checkboxes:
    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: Update labels based on checkboxes
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        with:
          script: |
            const body = context.payload.pull_request.body || "";

            const mapping = [
              { text: 'label: Breaking change', label: 'breaking-change' },
              { text: 'label: Non-breaking change', label: 'non-breaking-change' }
            ];

            for (const { text, label } of mapping) {
              await core.group(`Processing label: ${label}`, async () => {
                const isChecked = new RegExp(`- \\[x\\] ${text}`, 'i').test(body);

                if (isChecked) {
                  console.log(`Adding label: ${label}`);
                  await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    labels: [label]
                  });
                } else {
                  console.log(`Removing label: ${label} (if present)`);
                  try {
                    await github.rest.issues.removeLabel({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: context.issue.number,
                      name: label
                    });
                    console.log(`Removed label: ${label}`);
                  } catch (e) {
                    if (e.status !== 404) throw e;
                  }
                }
              });
            }
